// App.vue
<script setup lang="ts">
import { ref } from 'vue';
import { Tab } from './types';
import TabBar from './components/TabBar.vue';
import HomeScreen from './screens/HomeScreen.vue';
import CalendarScreen from './screens/CalendarScreen.vue';
import MessageScreen from './screens/MessageScreen.vue';
import ProfileScreen from './screens/ProfileScreen.vue';
import LicenseScreen from './screens/LicenseScreen.vue';

const activeTab = ref<Tab>(Tab.HOME);
const subPage = ref<string | null>(null);

const handleNavigate = (screen: string) => {
  subPage.value = screen;
};

const handleBack = () => {
  subPage.value = null;
};
</script>

<template>
  <div class="max-w-md mx-auto min-h-screen bg-gray-50 shadow-2xl relative overflow-hidden">
    <!-- Sub Page Rendering -->
    <LicenseScreen v-if="subPage === 'license'" @back="handleBack" />

    <!-- Main Tabs Rendering -->
    <template v-else>
      <HomeScreen v-if="activeTab === Tab.HOME" />
      <CalendarScreen v-else-if="activeTab === Tab.CALENDAR" />
      <MessageScreen v-else-if="activeTab === Tab.MESSAGE" />
      <ProfileScreen v-else-if="activeTab === Tab.PROFILE" @navigate="handleNavigate" />
      
      <!-- Tab Bar -->
      <TabBar :activeTab="activeTab" @update:activeTab="(val) => activeTab = val" />
    </template>
  </div>
</template>

// App.tsx
import React, { useState } from 'react';
import TabBar from './components/TabBar';
import HomeScreen from './screens/HomeScreen';
import CalendarScreen from './screens/CalendarScreen';
import MessageScreen from './screens/MessageScreen';
import ProfileScreen from './screens/ProfileScreen';
import { Tab } from './types';

const App: React.FC = () => {
  const [activeTab, setActiveTab] = useState<Tab>(Tab.HOME);

  const renderScreen = () => {
    switch (activeTab) {
      case Tab.HOME:
        return <HomeScreen />;
      case Tab.CALENDAR:
        return <CalendarScreen />;
      case Tab.MESSAGE:
        return <MessageScreen />;
      case Tab.PROFILE:
        return <ProfileScreen />;
      default:
        return <HomeScreen />;
    }
  };

  return (
    <div className="max-w-md mx-auto min-h-screen bg-gray-50 shadow-2xl relative overflow-hidden">
      {renderScreen()}
      <TabBar activeTab={activeTab} onTabChange={setActiveTab} />
    </div>
  );
};

export default App;
